name: Main

on:
  push:
    branches:
      - main

jobs:

  build-test-publish:
    uses: cyber-dojo-languages/reusable-actions-workflows/.github/workflows/build-image-per-arch.yml@main
    permissions:
      packages: write
      contents: read
